version: '3.9'

services:
  app:
    build:
      context: .
    ports:
      - 8501:8501
    volumes:
      - .:/app
    working_dir: /app







# version: '3.9'

# services:
#   app:
#     build:
#       context: .
#     ports:
#       - 8501:8501
#     volumes:
#       - .:/app
